name: battery-analytics-lab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scipy>=1.8.0
  - scikit-learn>=1.1.0
  - openpyxl>=3.0.0
  - pyyaml>=6.0
  - jupyter>=1.0.0
  - jupyterlab>=3.4.0
  - ipywidgets>=7.6.0
  - plotly>=5.0.0
  - xlrd>=2.0.0
  - xlsxwriter>=3.0.0
  - tqdm>=4.64.0
  - joblib>=1.1.0
  - numba>=0.56.0
  - dask>=2022.6.0
  - graphviz>=0.20.0
  - python-graphviz>=0.20.0
  - pip
  - pip:
    - pyarrow>=9.0.0
    - fastparquet>=0.8.0
    - xgboost>=1.6.0
    - lightgbm>=3.3.0
    - optuna>=3.0.0
    - shap>=0.41.0
    - phik>=0.12.0
    - missingno>=0.5.0
    - pandas-profiling>=3.2.0
    - great-expectations>=0.15.0